convert -resize 50% calibration2.png small/calibration2.png
convert -resize 50% calibration2_undistorted.png small/calibration2_undistorted.png
convert -resize 50% collage4_troubleshooting.png small/collage4_troubleshooting.png
convert -resize 50% placeholder_project_collage4.png small/placeholder_project_collage4.png
convert -resize 50% placeholder_project_output.png small/placeholder_project_output.png
convert -resize 50% test1_01_undistort.png small/test1_01_undistort.png
convert -resize 50% test1_02_gray.png small/test1_02_gray.png
convert -resize 50% test1_03_binary_sobelxy.png small/test1_03_binary_sobelxy.png
convert -resize 50% test1_04_binary_s_of_hls.png small/test1_04_binary_s_of_hls.png
convert -resize 50% test1_05_binaries_combined.png small/test1_05_binaries_combined.png
convert -resize 50% test1_06_skewed_rectangle.png small/test1_06_skewed_rectangle.png
convert -resize 50% test1_07_birds_eye_view.png small/test1_07_birds_eye_view.png
convert -resize 50% test1_09_histogram.png small/test1_09_histogram.png
convert -resize 50% test1_10_sliding_window.png small/test1_10_sliding_window.png
convert -resize 50% test1_11_colored_lane.png small/test1_11_colored_lane.png
convert -resize 50% test1.png small/test1.png
convert -resize 50% test1_result.png small/test1_result.png
